// Code generated by protoc-gen-go. DO NOT EDIT.
// source: center_server.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//中心服务器通知地图服务器角色进入地图
type RoleLoginSuccess struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleLoginSuccess) Reset()         { *m = RoleLoginSuccess{} }
func (m *RoleLoginSuccess) String() string { return proto.CompactTextString(m) }
func (*RoleLoginSuccess) ProtoMessage()    {}
func (*RoleLoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_91fb75f26ebeb9d0, []int{0}
}

func (m *RoleLoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleLoginSuccess.Unmarshal(m, b)
}
func (m *RoleLoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleLoginSuccess.Marshal(b, m, deterministic)
}
func (m *RoleLoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleLoginSuccess.Merge(m, src)
}
func (m *RoleLoginSuccess) XXX_Size() int {
	return xxx_messageInfo_RoleLoginSuccess.Size(m)
}
func (m *RoleLoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleLoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_RoleLoginSuccess proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RoleLoginSuccess)(nil), "msg.role_login_success")
}

func init() { proto.RegisterFile("center_server.proto", fileDescriptor_91fb75f26ebeb9d0) }

var fileDescriptor_91fb75f26ebeb9d0 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4e, 0xcd, 0x2b,
	0x49, 0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xce, 0x2d, 0x4e, 0x57, 0x12, 0xe1, 0x12, 0x2a, 0xca, 0xcf, 0x49, 0x8d, 0xcf, 0xc9, 0x4f,
	0xcf, 0xcc, 0x8b, 0x2f, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x4e, 0x62, 0x03, 0xab, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x7a, 0xc6, 0x85, 0x38, 0x00, 0x00, 0x00,
}
