// Code generated by protoc-gen-go. DO NOT EDIT.
// source: center_server.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//游戏服务器通知中心服务器初始化完成
type NotifyServerInited struct {
	LoadedMaps           []int32  `protobuf:"varint,1,rep,packed,name=loadedMaps,proto3" json:"loadedMaps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyServerInited) Reset()         { *m = NotifyServerInited{} }
func (m *NotifyServerInited) String() string { return proto.CompactTextString(m) }
func (*NotifyServerInited) ProtoMessage()    {}
func (*NotifyServerInited) Descriptor() ([]byte, []int) {
	return fileDescriptor_91fb75f26ebeb9d0, []int{0}
}

func (m *NotifyServerInited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServerInited.Unmarshal(m, b)
}
func (m *NotifyServerInited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServerInited.Marshal(b, m, deterministic)
}
func (m *NotifyServerInited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServerInited.Merge(m, src)
}
func (m *NotifyServerInited) XXX_Size() int {
	return xxx_messageInfo_NotifyServerInited.Size(m)
}
func (m *NotifyServerInited) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServerInited.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServerInited proto.InternalMessageInfo

func (m *NotifyServerInited) GetLoadedMaps() []int32 {
	if m != nil {
		return m.LoadedMaps
	}
	return nil
}

//中心服务器通知游戏服务器角色进入地图
type NotifyRoleEnter struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RoleId               string   `protobuf:"bytes,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRoleEnter) Reset()         { *m = NotifyRoleEnter{} }
func (m *NotifyRoleEnter) String() string { return proto.CompactTextString(m) }
func (*NotifyRoleEnter) ProtoMessage()    {}
func (*NotifyRoleEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_91fb75f26ebeb9d0, []int{1}
}

func (m *NotifyRoleEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRoleEnter.Unmarshal(m, b)
}
func (m *NotifyRoleEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRoleEnter.Marshal(b, m, deterministic)
}
func (m *NotifyRoleEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRoleEnter.Merge(m, src)
}
func (m *NotifyRoleEnter) XXX_Size() int {
	return xxx_messageInfo_NotifyRoleEnter.Size(m)
}
func (m *NotifyRoleEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRoleEnter.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRoleEnter proto.InternalMessageInfo

func (m *NotifyRoleEnter) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *NotifyRoleEnter) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NotifyRoleEnter) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

//游戏服务器通知中心服务器角色已经可以进入地图了
type NotifyRoleEntered struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRoleEntered) Reset()         { *m = NotifyRoleEntered{} }
func (m *NotifyRoleEntered) String() string { return proto.CompactTextString(m) }
func (*NotifyRoleEntered) ProtoMessage()    {}
func (*NotifyRoleEntered) Descriptor() ([]byte, []int) {
	return fileDescriptor_91fb75f26ebeb9d0, []int{2}
}

func (m *NotifyRoleEntered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRoleEntered.Unmarshal(m, b)
}
func (m *NotifyRoleEntered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRoleEntered.Marshal(b, m, deterministic)
}
func (m *NotifyRoleEntered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRoleEntered.Merge(m, src)
}
func (m *NotifyRoleEntered) XXX_Size() int {
	return xxx_messageInfo_NotifyRoleEntered.Size(m)
}
func (m *NotifyRoleEntered) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRoleEntered.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRoleEntered proto.InternalMessageInfo

func (m *NotifyRoleEntered) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*NotifyServerInited)(nil), "proto.notify_server_inited")
	proto.RegisterType((*NotifyRoleEnter)(nil), "proto.notify_role_enter")
	proto.RegisterType((*NotifyRoleEntered)(nil), "proto.notify_role_entered")
}

func init() { proto.RegisterFile("center_server.proto", fileDescriptor_91fb75f26ebeb9d0) }

var fileDescriptor_91fb75f26ebeb9d0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4e, 0xcd, 0x2b,
	0x49, 0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x53, 0x4a, 0x66, 0x5c, 0x22, 0x79, 0xf9, 0x25, 0x99, 0x69, 0x95, 0x50, 0xd9, 0xf8,
	0xcc, 0xbc, 0xcc, 0x92, 0xd4, 0x14, 0x21, 0x39, 0x2e, 0xae, 0x9c, 0xfc, 0xc4, 0x94, 0xd4, 0x14,
	0xdf, 0xc4, 0x82, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xd6, 0x20, 0x24, 0x11, 0xa5, 0x48, 0x2e,
	0x41, 0xa8, 0xbe, 0xa2, 0xfc, 0x9c, 0xd4, 0x78, 0xb0, 0x05, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9,
	0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x18, 0x17, 0x5b,
	0x69, 0x71, 0x6a, 0x91, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x18, 0xca, 0x03, 0x89, 0x83, 0xf4, 0x7a,
	0xa6, 0x48, 0x30, 0x43, 0xc4, 0x21, 0x3c, 0x25, 0x5d, 0x2e, 0x61, 0x0c, 0xa3, 0x53, 0x53, 0x90,
	0x8c, 0x61, 0x44, 0x36, 0x26, 0x89, 0x0d, 0xec, 0x11, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x53, 0xc0, 0x8c, 0x6b, 0xe6, 0x00, 0x00, 0x00,
}
