// Code generated by protoc-gen-go. DO NOT EDIT.
// source: center_client.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//登录请求
type ReqLogin struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//登录返回
type RspLogin struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspLogin) Reset()         { *m = RspLogin{} }
func (m *RspLogin) String() string { return proto.CompactTextString(m) }
func (*RspLogin) ProtoMessage()    {}
func (*RspLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{1}
}

func (m *RspLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspLogin.Unmarshal(m, b)
}
func (m *RspLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspLogin.Marshal(b, m, deterministic)
}
func (m *RspLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspLogin.Merge(m, src)
}
func (m *RspLogin) XXX_Size() int {
	return xxx_messageInfo_RspLogin.Size(m)
}
func (m *RspLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RspLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RspLogin proto.InternalMessageInfo

func (m *RspLogin) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

//获取角色列表
type ReqRolelist struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRolelist) Reset()         { *m = ReqRolelist{} }
func (m *ReqRolelist) String() string { return proto.CompactTextString(m) }
func (*ReqRolelist) ProtoMessage()    {}
func (*ReqRolelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{2}
}

func (m *ReqRolelist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRolelist.Unmarshal(m, b)
}
func (m *ReqRolelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRolelist.Marshal(b, m, deterministic)
}
func (m *ReqRolelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRolelist.Merge(m, src)
}
func (m *ReqRolelist) XXX_Size() int {
	return xxx_messageInfo_ReqRolelist.Size(m)
}
func (m *ReqRolelist) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRolelist.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRolelist proto.InternalMessageInfo

//角色列表中的表项定义
type LoginRoleInfo struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                uint32   `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Sex                  uint32   `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	MapId                uint32   `protobuf:"varint,5,opt,name=mapId,proto3" json:"mapId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRoleInfo) Reset()         { *m = LoginRoleInfo{} }
func (m *LoginRoleInfo) String() string { return proto.CompactTextString(m) }
func (*LoginRoleInfo) ProtoMessage()    {}
func (*LoginRoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{3}
}

func (m *LoginRoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRoleInfo.Unmarshal(m, b)
}
func (m *LoginRoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRoleInfo.Marshal(b, m, deterministic)
}
func (m *LoginRoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRoleInfo.Merge(m, src)
}
func (m *LoginRoleInfo) XXX_Size() int {
	return xxx_messageInfo_LoginRoleInfo.Size(m)
}
func (m *LoginRoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRoleInfo proto.InternalMessageInfo

func (m *LoginRoleInfo) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *LoginRoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRoleInfo) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LoginRoleInfo) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *LoginRoleInfo) GetMapId() uint32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

//返回角色列表
type RspRolelist struct {
	RetCode              int32            `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	RoleNum              uint32           `protobuf:"varint,2,opt,name=role_num,json=roleNum,proto3" json:"role_num,omitempty"`
	RoleInfos            []*LoginRoleInfo `protobuf:"bytes,3,rep,name=roleInfos,proto3" json:"roleInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RspRolelist) Reset()         { *m = RspRolelist{} }
func (m *RspRolelist) String() string { return proto.CompactTextString(m) }
func (*RspRolelist) ProtoMessage()    {}
func (*RspRolelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{4}
}

func (m *RspRolelist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRolelist.Unmarshal(m, b)
}
func (m *RspRolelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRolelist.Marshal(b, m, deterministic)
}
func (m *RspRolelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRolelist.Merge(m, src)
}
func (m *RspRolelist) XXX_Size() int {
	return xxx_messageInfo_RspRolelist.Size(m)
}
func (m *RspRolelist) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRolelist.DiscardUnknown(m)
}

var xxx_messageInfo_RspRolelist proto.InternalMessageInfo

func (m *RspRolelist) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RspRolelist) GetRoleNum() uint32 {
	if m != nil {
		return m.RoleNum
	}
	return 0
}

func (m *RspRolelist) GetRoleInfos() []*LoginRoleInfo {
	if m != nil {
		return m.RoleInfos
	}
	return nil
}

//客户端请求创建角色
type ReqCreateRole struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  uint32   `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateRole) Reset()         { *m = ReqCreateRole{} }
func (m *ReqCreateRole) String() string { return proto.CompactTextString(m) }
func (*ReqCreateRole) ProtoMessage()    {}
func (*ReqCreateRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{5}
}

func (m *ReqCreateRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateRole.Unmarshal(m, b)
}
func (m *ReqCreateRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateRole.Marshal(b, m, deterministic)
}
func (m *ReqCreateRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateRole.Merge(m, src)
}
func (m *ReqCreateRole) XXX_Size() int {
	return xxx_messageInfo_ReqCreateRole.Size(m)
}
func (m *ReqCreateRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateRole.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateRole proto.InternalMessageInfo

func (m *ReqCreateRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateRole) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

//服务端相应创建角色
type RspCreateRole struct {
	RetCode              int32          `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Info                 *LoginRoleInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RspCreateRole) Reset()         { *m = RspCreateRole{} }
func (m *RspCreateRole) String() string { return proto.CompactTextString(m) }
func (*RspCreateRole) ProtoMessage()    {}
func (*RspCreateRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{6}
}

func (m *RspCreateRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCreateRole.Unmarshal(m, b)
}
func (m *RspCreateRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCreateRole.Marshal(b, m, deterministic)
}
func (m *RspCreateRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCreateRole.Merge(m, src)
}
func (m *RspCreateRole) XXX_Size() int {
	return xxx_messageInfo_RspCreateRole.Size(m)
}
func (m *RspCreateRole) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCreateRole.DiscardUnknown(m)
}

var xxx_messageInfo_RspCreateRole proto.InternalMessageInfo

func (m *RspCreateRole) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RspCreateRole) GetInfo() *LoginRoleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

//删除角色
type ReqDelRole struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDelRole) Reset()         { *m = ReqDelRole{} }
func (m *ReqDelRole) String() string { return proto.CompactTextString(m) }
func (*ReqDelRole) ProtoMessage()    {}
func (*ReqDelRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{7}
}

func (m *ReqDelRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDelRole.Unmarshal(m, b)
}
func (m *ReqDelRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDelRole.Marshal(b, m, deterministic)
}
func (m *ReqDelRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDelRole.Merge(m, src)
}
func (m *ReqDelRole) XXX_Size() int {
	return xxx_messageInfo_ReqDelRole.Size(m)
}
func (m *ReqDelRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDelRole.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDelRole proto.InternalMessageInfo

func (m *ReqDelRole) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type RspDelRole struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	RoleId               string   `protobuf:"bytes,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspDelRole) Reset()         { *m = RspDelRole{} }
func (m *RspDelRole) String() string { return proto.CompactTextString(m) }
func (*RspDelRole) ProtoMessage()    {}
func (*RspDelRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{8}
}

func (m *RspDelRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspDelRole.Unmarshal(m, b)
}
func (m *RspDelRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspDelRole.Marshal(b, m, deterministic)
}
func (m *RspDelRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspDelRole.Merge(m, src)
}
func (m *RspDelRole) XXX_Size() int {
	return xxx_messageInfo_RspDelRole.Size(m)
}
func (m *RspDelRole) XXX_DiscardUnknown() {
	xxx_messageInfo_RspDelRole.DiscardUnknown(m)
}

var xxx_messageInfo_RspDelRole proto.InternalMessageInfo

func (m *RspDelRole) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RspDelRole) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

//选择角色进入游戏地图
type ReqSelectRole struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSelectRole) Reset()         { *m = ReqSelectRole{} }
func (m *ReqSelectRole) String() string { return proto.CompactTextString(m) }
func (*ReqSelectRole) ProtoMessage()    {}
func (*ReqSelectRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{9}
}

func (m *ReqSelectRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSelectRole.Unmarshal(m, b)
}
func (m *ReqSelectRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSelectRole.Marshal(b, m, deterministic)
}
func (m *ReqSelectRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSelectRole.Merge(m, src)
}
func (m *ReqSelectRole) XXX_Size() int {
	return xxx_messageInfo_ReqSelectRole.Size(m)
}
func (m *ReqSelectRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSelectRole.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSelectRole proto.InternalMessageInfo

func (m *ReqSelectRole) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type RspSelectRole struct {
	RetCode              int32    `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	RoleId               string   `protobuf:"bytes,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	MapId                uint32   `protobuf:"varint,3,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ServerIp             string   `protobuf:"bytes,5,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ServerPort           string   `protobuf:"bytes,6,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSelectRole) Reset()         { *m = RspSelectRole{} }
func (m *RspSelectRole) String() string { return proto.CompactTextString(m) }
func (*RspSelectRole) ProtoMessage()    {}
func (*RspSelectRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_832f0ed572a10b2d, []int{10}
}

func (m *RspSelectRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSelectRole.Unmarshal(m, b)
}
func (m *RspSelectRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSelectRole.Marshal(b, m, deterministic)
}
func (m *RspSelectRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSelectRole.Merge(m, src)
}
func (m *RspSelectRole) XXX_Size() int {
	return xxx_messageInfo_RspSelectRole.Size(m)
}
func (m *RspSelectRole) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSelectRole.DiscardUnknown(m)
}

var xxx_messageInfo_RspSelectRole proto.InternalMessageInfo

func (m *RspSelectRole) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RspSelectRole) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *RspSelectRole) GetMapId() uint32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *RspSelectRole) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RspSelectRole) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *RspSelectRole) GetServerPort() string {
	if m != nil {
		return m.ServerPort
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "proto.req_login")
	proto.RegisterType((*RspLogin)(nil), "proto.rsp_login")
	proto.RegisterType((*ReqRolelist)(nil), "proto.req_rolelist")
	proto.RegisterType((*LoginRoleInfo)(nil), "proto.login_role_info")
	proto.RegisterType((*RspRolelist)(nil), "proto.rsp_rolelist")
	proto.RegisterType((*ReqCreateRole)(nil), "proto.req_create_role")
	proto.RegisterType((*RspCreateRole)(nil), "proto.rsp_create_role")
	proto.RegisterType((*ReqDelRole)(nil), "proto.req_del_role")
	proto.RegisterType((*RspDelRole)(nil), "proto.rsp_del_role")
	proto.RegisterType((*ReqSelectRole)(nil), "proto.req_select_role")
	proto.RegisterType((*RspSelectRole)(nil), "proto.rsp_select_role")
}

func init() { proto.RegisterFile("center_client.proto", fileDescriptor_832f0ed572a10b2d) }

var fileDescriptor_832f0ed572a10b2d = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x45, 0x96, 0x65, 0x5b, 0x63, 0xbb, 0x2e, 0xdb, 0x62, 0xb6, 0xf4, 0x50, 0xb3, 0xa5, 0xc5,
	0xed, 0xc1, 0x87, 0xb6, 0xd0, 0x6b, 0xa1, 0x27, 0x5f, 0x4a, 0xd1, 0x25, 0x47, 0xe1, 0x48, 0xe3,
	0x20, 0xb2, 0xda, 0x55, 0x56, 0x6b, 0x93, 0x90, 0x6f, 0xca, 0x3f, 0x86, 0x9d, 0x95, 0x2d, 0x25,
	0xa0, 0x40, 0x4e, 0xd2, 0x9b, 0x7d, 0x3b, 0xef, 0xbd, 0x99, 0x85, 0x77, 0x19, 0x2a, 0x8b, 0x26,
	0xcd, 0x64, 0x81, 0xca, 0x6e, 0x2a, 0xa3, 0xad, 0x66, 0x11, 0x7d, 0xc4, 0x67, 0x88, 0x0d, 0xde,
	0xa4, 0x52, 0x5f, 0x15, 0x8a, 0x2d, 0x61, 0x74, 0xa8, 0xd1, 0x6c, 0x73, 0x1e, 0xac, 0x82, 0x75,
	0x9c, 0x34, 0x48, 0x7c, 0x81, 0xd8, 0xd4, 0x55, 0x43, 0xe2, 0x30, 0x36, 0x68, 0xff, 0xea, 0x1c,
	0x89, 0x15, 0x25, 0x27, 0x28, 0xde, 0xc0, 0xcc, 0xf5, 0x32, 0x5a, 0xa2, 0x2c, 0x6a, 0x2b, 0xee,
	0x61, 0x41, 0x57, 0xa8, 0x92, 0x16, 0x6a, 0xaf, 0x9d, 0x82, 0x03, 0xad, 0x82, 0x47, 0x8c, 0xc1,
	0x50, 0xed, 0x4a, 0xe4, 0x03, 0xaa, 0xd2, 0x3f, 0x7b, 0x0f, 0x91, 0xc4, 0x23, 0x4a, 0x1e, 0xae,
	0x82, 0xf5, 0x3c, 0xf1, 0x80, 0xbd, 0x85, 0xb0, 0xc6, 0x5b, 0x3e, 0xa4, 0x9a, 0xfb, 0x75, 0xbc,
	0x72, 0x57, 0x6d, 0x73, 0x1e, 0x79, 0x1e, 0x01, 0x71, 0x07, 0x33, 0xe7, 0xf9, 0x64, 0xa6, 0xdf,
	0x36, 0xfb, 0x00, 0x13, 0x32, 0xa8, 0x0e, 0x25, 0xe9, 0xcf, 0x93, 0xb1, 0xc3, 0xff, 0x0e, 0x25,
	0xfb, 0x05, 0x31, 0x19, 0x54, 0x7b, 0x5d, 0xf3, 0x70, 0x15, 0xae, 0xa7, 0x3f, 0x96, 0x7e, 0x7e,
	0x9b, 0x67, 0xc9, 0x92, 0x96, 0x28, 0x7e, 0xc3, 0xc2, 0xcd, 0x21, 0x33, 0xb8, 0xb3, 0x48, 0x94,
	0x73, 0xbe, 0xa0, 0x93, 0xaf, 0x49, 0x32, 0x38, 0x27, 0x11, 0x17, 0xb0, 0x70, 0x9e, 0xbb, 0x17,
	0xfb, 0x6d, 0x7f, 0x87, 0xa1, 0x13, 0xa6, 0xfb, 0xfd, 0xb6, 0x88, 0x23, 0xbe, 0xfa, 0xcd, 0xe4,
	0x28, 0x7d, 0xd7, 0x9e, 0x35, 0x88, 0x3f, 0x7e, 0x68, 0x67, 0x5e, 0xbf, 0x7a, 0xdb, 0x61, 0xf0,
	0xa4, 0xc3, 0x37, 0x9f, 0xbd, 0x46, 0x89, 0x99, 0x7d, 0x59, 0xec, 0x21, 0xf0, 0x71, 0xbb, 0xdc,
	0x57, 0x0b, 0xb6, 0xdb, 0x0f, 0x3b, 0xdb, 0x77, 0x55, 0xab, 0xaf, 0x51, 0xd1, 0x3b, 0x89, 0x13,
	0x0f, 0xd8, 0x47, 0x88, 0x6b, 0x34, 0x47, 0x34, 0x69, 0x51, 0xd1, 0x6b, 0x89, 0x93, 0x89, 0x2f,
	0x6c, 0x2b, 0xf6, 0x09, 0xa6, 0xcd, 0x61, 0xa5, 0x8d, 0xe5, 0x23, 0x3a, 0x06, 0x5f, 0xfa, 0xaf,
	0x8d, 0xbd, 0x1c, 0xd1, 0x84, 0x7f, 0x3e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x08, 0x78, 0xb4, 0x54,
	0x4f, 0x03, 0x00, 0x00,
}
